SecRule ARGS|REQUEST_URI|REQUEST_HEADERS "@contains evilmonkey" \
      "id:3001,\
      phase:2,\
      deny,\
      status:403,\
      t:none,t:urlDecodeUni,\
      msg:'Evil Monkey Detected',\
      logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\
      tag:'application-multi',\
      tag:'language-multi',\
      tag:'platform-multi',\
      tag:'monkey-attack',\
      severity:'CRITICAL'"